services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - ./backend/tasks.json:/app/tasks.json
    environment:
      - FLASK_ENV=development

  frontend:
    build: ./frontend/taskmanager
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/taskmanager:/app
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=http://localhost:5000/api
      - HOST=0.0.0.0
      - WDS_SOCKET_HOST=localhost
    depends_on:
      - backend

